Ubiquity 22.04.19
/usr/lib/ubiquity/ubiquity/frontend/gtk_components/nmwidgets.py:7: PyGIWarning: NM was imported without specifying a version first. Use gi.require_version('NM', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import NM, NMA

(ubiquity:1458): Gtk-WARNING **: 03:42:17.302: GtkBox does not have a child property called left_attach

(ubiquity:1458): Gtk-WARNING **: 03:42:17.302: GtkBox does not have a child property called width

(ubiquity:1458): Gtk-WARNING **: 03:42:17.302: GtkBox does not have a child property called height

(ubiquity:1458): Gtk-WARNING **: 03:42:17.302: GtkBox does not have a child property called width

(ubiquity:1458): Gtk-WARNING **: 03:42:17.302: GtkBox does not have a child property called height

(ubiquity:1458): Gtk-WARNING **: 03:42:17.302: GtkGrid does not have a child property called expand

(ubiquity:1458): Gtk-WARNING **: 03:42:17.302: GtkGrid does not have a child property called fill

(ubiquity:1458): Gtk-WARNING **: 03:42:17.302: GtkGrid does not have a child property called position
No such schema “org.gnome.nautilus.desktop”
expected value:
  (empty input)
  ^
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
/usr/lib/ubiquity/ubiquity/misc.py:710: PyGIWarning: Xkl was imported without specifying a version first. Use gi.require_version('Xkl', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Xkl, GdkX11
update_release_notes_label()
update_release_notes_label()
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
Could not translate page (prepare): 'NoneType' object has no attribute 'replace'
Your console font configuration will be updated the next time your system
boots. If you want to update it now, run 'setupcon' from a virtual console.
update-initramfs is disabled since running on read-only media
debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.dat: Permission denied
No such schema “com.canonical.indicator.session”
No such key “active”
No such schema “org.gnome.nautilus.desktop”
Ubiquity 22.04.19
/usr/lib/ubiquity/ubiquity/frontend/gtk_components/nmwidgets.py:7: PyGIWarning: NM was imported without specifying a version first. Use gi.require_version('NM', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import NM, NMA

(ubiquity:5503): Gtk-WARNING **: 03:43:07.013: GtkBox does not have a child property called left_attach

(ubiquity:5503): Gtk-WARNING **: 03:43:07.013: GtkBox does not have a child property called width

(ubiquity:5503): Gtk-WARNING **: 03:43:07.013: GtkBox does not have a child property called height

(ubiquity:5503): Gtk-WARNING **: 03:43:07.013: GtkBox does not have a child property called width

(ubiquity:5503): Gtk-WARNING **: 03:43:07.013: GtkBox does not have a child property called height

(ubiquity:5503): Gtk-WARNING **: 03:43:07.013: GtkGrid does not have a child property called expand

(ubiquity:5503): Gtk-WARNING **: 03:43:07.013: GtkGrid does not have a child property called fill

(ubiquity:5503): Gtk-WARNING **: 03:43:07.013: GtkGrid does not have a child property called position
No such schema “org.gnome.nautilus.desktop”
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
update_release_notes_label()
update_release_notes_label()
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
Could not translate page (prepare): 'NoneType' object has no attribute 'replace'
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
/usr/lib/ubiquity/plugins/ubi-console-setup.py:70: Warning: Source ID 388 was not found when attempting to remove it
  GLib.source_remove(self.keyboard_layout_timeout_id)
/usr/lib/ubiquity/plugins/ubi-console-setup.py:72: Warning: Source ID 391 was not found when attempting to remove it
  GLib.source_remove(self.keyboard_variant_timeout_id)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
No such schema “com.canonical.indicator.session”
No such schema “com.canonical.indicator.session”
No such schema “com.canonical.indicator.session”
No such schema “com.canonical.indicator.session”
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
/usr/lib/ubiquity/plugins/ubi-timezone.py:96: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, GLib, Soup
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
XDG_RUNTIME_DIR (/run/user/999) is not owned by us (uid 0), but by uid 999! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)

(ubiquity:5503): Gtk-CRITICAL **: 11:46:14.286: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(ubiquity:5503): Gtk-CRITICAL **: 11:46:16.520: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
